### ISSUE TITLE
Header missing END card

### ISSUE THREAD

**Issue by Lraynard** [apchsh/SAFPhot#2]
[lr182@alice04 saao_scripts]$ python safphot.py -c SHA -d ../NG1421+0000_04553_all
Namespace(c=['SHA'], d=['../NG1421+0000_04553_all'])
Searching directory ../NG1421+0000_04553_all
37 files found.
Traceback (most recent call last):
  File "safphot.py", line 39, in <module>
    files = ps.fits_sort(args.d[0], args.c[0], verbose=True)
  File "/scratch/ngts/lr182/follow_up/saao_scripts/photsort.py", line 40, in __init__
    self.search()
  File "/scratch/ngts/lr182/follow_up/saao_scripts/photsort.py", line 85, in search
    f.close()
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 909, in close
    while self._read_next_hdu():
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1135, in _read_next_hdu
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 329, in readfrom
    **kwargs)
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 394, in _readfrom_internal
    header = Header.fromfile(data, endcard=not ignore_missing_end)
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/header.py", line 450, in fromfile
    padding)[1]
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/header.py", line 519, in _from_blocks
    raise IOError('Header missing END card.')
IOError: Header missing END card.

**Fixed by changing line 116 of photsort.py**
 f = fits.open(file_, ignore_missing_end=True)

**Comment by apchsh** [comment]
This is weird? Are you running it over a corrupted fits file?
