### ISSUE TITLE
This probably means that Tcl wasn't installed properly.

### ISSUE THREAD

**Issue by Lraynard** [apchsh/SAFPhot#4]
Reduction and unpacking complete.
Processing photometry on NG1421+0000_4553_V_-_Green
Starting photometry for NG1421+0000_4553_V_-_Green.
Traceback (most recent call last):
  File "safphot.py", line 55, in <module>
    ph.run_phot(dir_, item)
  File "/scratch/ngts/lr182/follow_up/saao_scripts/phot.py", line 187, in run_phot
    star_loc_plot(path.join(dir_, name +'.png'), flux,objects['x'], objects['y'], index)
  File "/scratch/ngts/lr182/follow_up/saao_scripts/phot.py", line 120, in star_loc_plot
    fig = plt.figure()
  File "/home/l/lr182/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/home/l/lr182/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/home/l/lr182/.local/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib64/python2.7/lib-tk/Tkinter.py", line 1745, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /star-2016A/lib/tcl8.5 /usr/lib/tcl8.5 /lib/tcl8.5 /usr/library /library /tcl8.5.16/library /tcl8.5.16/library

This probably means that Tcl wasn't installed properly.

**Comment by apchsh** [comment]
Yeah I don't think this is an error with the pipeline.
