### ISSUE TITLE
Invalid dimensions for image data

### ISSUE THREAD

**Issue by Lraynard** [apchsh/SAFPhot#5]
Reduction and unpacking complete.
Processing photometry on NG1421+0000_4553_V_-_Green
Starting photometry for NG1421+0000_4553_V_-_Green.
Traceback (most recent call last):
  File "safphot.py", line 55, in <module>
    ph.run_phot(dir_, item)
  File "/scratch/ngts/lr182/follow_up/saao_scripts/phot.py", line 187, in run_phot
    star_loc_plot(path.join(dir_, name +'.png'), flux,objects['x'], objects['y'], index)
  File "/scratch/ngts/lr182/follow_up/saao_scripts/phot.py", line 121, in star_loc_plot
    plt.imshow(data, vmin=dmean-1*dstd, vmax=dmean+2*dstd, cmap=plt.get_cmap('gray'))
  File "/home/l/lr182/.local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3158, in imshow
    **kwargs)
  File "/home/l/lr182/.local/lib/python2.7/site-packages/matplotlib/__init__.py", line 1892, in inner
    return func(ax, *args, **kwargs)
  File "/home/l/lr182/.local/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 5118, in imshow
    im.set_data(X)
  File "/home/l/lr182/.local/lib/python2.7/site-packages/matplotlib/image.py", line 549, in set_data
    raise TypeError("Invalid dimensions for image data")
TypeError: Invalid dimensions for image data

**Comment by apchsh** [comment]
Looks like it failed to find any stars. Was this a cloudy image?

**Comment by Lraynard** [comment]
Nah it's because it can't generate the numbered object plot.
L187 of phot.py:
star_loc_plot(path.join(dir_, name +'.png'), flux,objects['x'], objects['y'], index)

should be 'data_sub' instead of 'flux' in the call

**Comment by apchsh** [comment]
Fixed. Cheers
