### ISSUE TITLE
IOError: Header missing END card.

### ISSUE THREAD

**Issue by Lraynard** [apchsh/SAFPhot#9]
[lr182@alice03 saao_scripts]$ python safphot.py -c SHA -d ../NG1421+0000_04553_all
Namespace(c=['SHA'], d=['../NG1421+0000_04553_all'])
Searching directory ../NG1421+0000_04553_all
37 files found.
Traceback (most recent call last):
  File "safphot.py", line 39, in <module>
    files = ps.fits_sort(args.d[0], args.c[0], verbose=True)
  File "/scratch/ngts/lr182/follow_up/saao_scripts/photsort.py", line 40, in __init__
    self.search()
  File "/scratch/ngts/lr182/follow_up/saao_scripts/photsort.py", line 85, in search
    f.close()
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 909, in close
    while self._read_next_hdu():
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 1135, in _read_next_hdu
    hdu = _BaseHDU.readfrom(fileobj, **kwargs)
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 329, in readfrom
    **kwargs)
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/hdu/base.py", line 394, in _readfrom_internal
    header = Header.fromfile(data, endcard=not ignore_missing_end)
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/header.py", line 450, in fromfile
    padding)[1]
  File "/home/l/lr182/.local/lib/python2.7/site-packages/astropy/io/fits/header.py", line 519, in _from_blocks
    raise IOError('Header missing END card.')
IOError: Header missing END card.

**Comment by Lraynard** [comment]
So i think this is when there are trailing bytes.
Fixed by changing L58 in photsort.py:

 f = fits.open(file_, ignore_missing_end=True)

Added to the fitsio.read call in phot.py also just in case.

**Comment by Lraynard** [comment]
Ok so while these edits allowed the program to continue running, the flux output became screwed up. If i remove the edit in the phot.py file, delete directories and re-run the pipeline I get the following error message:

Searching directory ../NG1421+0000_04553_all/
861 files found.
WARNING: VerifyWarning: Error validating header for HDU #1 (note: Astropy uses zero-based indexing).
    Header size is not multiple of 2880: 1
There may be extra bytes after the last HDU or the file is corrupted. [astropy.io.fits.hdu.hdulist]
Files sorted.

A clue?

**Comment by apchsh** [comment]
Not sure what's going on here. I've never had problems with headers/file corruption with any of the files I have from previous runs. Is it possible that an action was terminated halfway resulting in a corrupted file?

**Comment by apchsh** [comment]
Closing this issue, as it was due to a corrupt file.
